# -*- coding: utf-8 -*-
QUIZZES = {}

def q(qid, qtype, question, options, correct, explanation):
    return {"id": qid, "type": qtype, "question": question, "options": options,
            "correct": correct, "explanation": explanation}

QUIZZES["p3-l01-create-table"] = [
    q("q1", "single", "Какая SQL-команда относится к DDL?",
      ["CREATE TABLE", "SELECT", "INSERT", "GRANT"], [0],
      "CREATE TABLE определяет структуру — это DDL."),
    q("q2", "single", "Что делает SERIAL в PostgreSQL?",
      ["Автоинкремент целого числа через sequence", "Строковый тип фиксированной длины",
       "Создаёт внешний ключ", "Шифрует столбец"], [0],
      "SERIAL = INTEGER + автоматическая последовательность."),
    q("q3", "single", "Зачем CREATE TABLE IF NOT EXISTS?",
      ["Избежать ошибки при повторном создании", "Ускорить SELECT", "Добавить индекс", "Включить транзакцию"], [0],
      "IF NOT EXISTS делает скрипт идемпотентным."),
    q("q4", "single", "Таблица student_in_group реализует связь:",
      ["Многие-ко-многим", "Один-к-одному", "Только иерархию", "Секционирование"], [0],
      "Связующая таблица с составным PK — классика M:N."),
    q("q5", "multi", "Что можно указать в CREATE TABLE? (все верные)",
      ["Имя столбца и тип", "PRIMARY KEY", "REFERENCES на другую таблицу", "COMMENT через отдельную команду"], [0, 1, 2],
      "COMMENT задаётся отдельно; остальное — в определении таблицы."),
    q("q6", "single", "SET search_path нужен для:",
      ["Указания схемы по умолчанию для объектов", "Сортировки результатов",
       "Установки уровня изоляции", "Создания индекса"], [0],
      "search_path определяет порядок поиска схем."),
]

QUIZZES["p3-l02-data-types"] = [
    q("q1", "single", "Какой тип выбрать для денежных сумм с копейками?",
      ["NUMERIC(12,2)", "REAL", "TEXT", "BOOLEAN"], [0],
      "NUMERIC — точная арифметика без ошибок float."),
    q("q2", "single", "Чем TEXT отличается от VARCHAR(n) в PostgreSQL?",
      ["Практически одинаковы по хранению; VARCHAR ограничивает длину в схеме", "TEXT не хранит кириллицу",
       "VARCHAR быстрее на порядок", "TEXT не допускает NULL"], [0],
      "В PG разница в основном декларативная."),
    q("q3", "single", "TIMESTAMPTZ хранит:",
      ["Метку времени с учётом часового пояса", "Только дату", "Интервал", "JSON"], [0],
      "TZ = with time zone."),
    q("q4", "single", "NOT NULL означает:",
      ["Столбец обязан иметь значение в каждой строке", "Столбец уникален",
       "Столбец — первичный ключ", "Значение не может быть 0"], [0],
      "NULL — отсутствие значения; NOT NULL это запрещает."),
    q("q5", "single", "JSONB подходит для:",
      ["Полуструктурированных атрибутов", "Только первичных ключей",
       "Замены всех JOIN", "Индексов B-tree только"], [0],
      "JSONB — бинарный JSON с индексацией GIN."),
    q("q6", "multi", "Какие типы — числовые? (все верные)",
      ["INTEGER", "BIGINT", "NUMERIC", "INTERVAL"], [0, 1, 2],
      "INTERVAL — длительность, не число для счёта."),
]

QUIZZES["p3-l03-constraints"] = [
    q("q1", "single", "PRIMARY KEY гарантирует:",
      ["Уникальность и NOT NULL", "Только NOT NULL", "Только ссылку на другую таблицу", "Значение > 0"], [0],
      "PK = уникальный идентификатор строки."),
    q("q2", "single", "ON DELETE CASCADE означает:",
      ["Удаление родителя удаляет дочерние строки", "Запрет удаления родителя",
       "Обнуление FK", "Копирование строк"], [0],
      "CASCADE распространяет DELETE на зависимые таблицы."),
    q("q3", "single", "CHECK (grade BETWEEN 2 AND 5) — это:",
      ["Доменное ограничение", "Первичный ключ", "Внешний ключ", "Индекс"], [0],
      "CHECK проверяет условие на значение столбца."),
    q("q4", "single", "SQLSTATE при нарушении UNIQUE:",
      ["23505", "23503", "42P01", "08003"], [0],
      "23505 = unique_violation."),
    q("q5", "single", "Составной PRIMARY KEY (a, b) означает:",
      ["Пара (a,b) уникальна; a и b по отдельности могут повторяться", "a и b каждый уникален",
       "Только a уникален", "NULL допустим в обоих"], [0],
      "Уникальность — по комбинации столбцов."),
    q("q6", "multi", "Какие ограничения обеспечивают ссылочную целостность? (все верные)",
      ["FOREIGN KEY", "REFERENCES", "ON UPDATE CASCADE", "CHECK на email"], [0, 1, 2],
      "CHECK — доменная целостность, не ссылочная."),
]

QUIZZES["p3-l04-alter-table"] = [
    q("q1", "single", "Добавить столбец:",
      ["ALTER TABLE t ADD COLUMN c тип", "CREATE COLUMN", "INSERT COLUMN", "MODIFY TABLE"], [0],
      "Стандартный синтаксис PostgreSQL."),
    q("q2", "single", "ALTER COLUMN ... TYPE часто требует:",
      ["USING выражение преобразования", "TRUNCATE", "DROP DATABASE", "CROSS JOIN"], [0],
      "USING задаёт как старые значения преобразовать."),
    q("q3", "single", "RENAME TO меняет:",
      ["Имя таблицы или столбца", "Только тип данных", "Только схему БД", "Пользователя"], [0],
      "RENAME TO — переименование объектов."),
    q("q4", "single", "DROP COLUMN IF EXISTS:",
      ["Не выдаёт ошибку, если столбца нет", "Сохраняет данные столбца", "Создаёт backup", "Добавляет индекс"], [0],
      "IF EXISTS — идемпотентность."),
    q("q5", "single", "Добавить NOT NULL к столбцу с NULL в строках:",
      ["Сначала заполнить значения, потом SET NOT NULL", "Возможно сразу без подготовки",
       "Только через DROP TABLE", "Невозможно в PostgreSQL"], [0],
      "Все строки должны иметь значение перед NOT NULL."),
    q("q6", "single", "ADD CONSTRAINT UNIQUE (email) добавляет:",
      ["Ограничение уникальности", "Внешний ключ", "Триггер", "Представление"], [0],
      "UNIQUE — альтернативный ключ."),
]

QUIZZES["p3-l05-insert"] = [
    q("q1", "single", "INSERT ... RETURNING в PostgreSQL:",
      ["Возвращает вставленные строки", "Удаляет дубликаты", "Создаёт индекс", "Начинает транзакцию"], [0],
      "RETURNING удобен для получения SERIAL."),
    q("q2", "single", "INSERT INTO t SELECT ...",
      ["Копирует данные из результата запроса", "Создаёт VIEW", "Только обновляет", "Только удаляет"], [0],
      "INSERT-SELECT — массовая загрузка."),
    q("q3", "single", "ON CONFLICT DO UPDATE — это:",
      ["Upsert: вставка или обновление при конфликте", "Каскадное удаление",
       "Откат транзакции", "Создание FK"], [0],
      "PostgreSQL-расширение для upsert."),
    q("q4", "single", "Пропуск столбца в INSERT (без DEFAULT NOT NULL):",
      ["Ошибка", "Вставится NULL", "Вставится 0", "Вставится пустая строка"], [0],
      "NOT NULL без DEFAULT — ошибка при INSERT."),
    q("q5", "multi", "Способы вставки нескольких строк? (все верные)",
      ["Несколько tuples в VALUES", "INSERT ... SELECT", "Несколько отдельных INSERT", "TRUNCATE"], [0, 1, 2],
      "TRUNCATE удаляет, не вставляет."),
    q("q6", "single", "DEFAULT в INSERT означает:",
      ["Использовать значение по умолчанию столбца", "Вставить NULL всегда", "Пропустить строку", "Откат"], [0],
      "DEFAULT подставляет declared default или NULL."),
]

QUIZZES["p3-l06-update"] = [
    q("q1", "single", "UPDATE без WHERE:",
      ["Обновит все строки таблицы", "Обновит одну строку", "Ошибка синтаксиса", "Создаст VIEW"], [0],
      "Опасная операция — всегда проверяйте WHERE."),
    q("q2", "single", "UPDATE ... FROM в PostgreSQL:",
      ["Обновляет на основании другой таблицы", "Создаёт FK", "Только для VIEW", "Аналог INSERT"], [0],
      "FROM соединяет таблицы для условия обновления."),
    q("q3", "single", "RETURNING в UPDATE:",
      ["Возвращает изменённые строки", "Откатывает транзакцию", "Удаляет строки", "Создаёт trigger"], [0],
      "Как и в INSERT — видеть результат."),
    q("q4", "single", "Перед массовым UPDATE рекомендуется:",
      ["Проверить SELECT с тем же WHERE", "TRUNCATE", "DROP TABLE", "CROSS JOIN"], [0],
      "SELECT показывает, сколько строк затронуто."),
    q("q5", "single", "UPDATE нарушающий CHECK:",
      ["Отклоняется с ошибкой", "Игнорируется", "Автоматически исправляется", "Удаляет строку"], [0],
      "Constraints проверяются при UPDATE."),
    q("q6", "multi", "SET может обновлять: (все верные)",
      ["Один столбец", "Несколько столбцов", "Столбец через выражение", "Только PRIMARY KEY без условий"], [0, 1, 2],
      "PK тоже можно, но нужен осмысленный WHERE."),
]

QUIZZES["p3-l07-delete"] = [
    q("q1", "single", "DELETE vs TRUNCATE — главное отличие:",
      ["DELETE — построчно с WHERE; TRUNCATE — вся таблица быстро", "Нет отличий",
       "TRUNCATE поддерживает WHERE", "DELETE быстрее на больших таблицах"], [0],
      "TRUNCATE — DDL-подобная очистка."),
    q("q2", "single", "TRUNCATE ... RESTART IDENTITY:",
      ["Сбрасывает счётчики SERIAL", "Удаляет схему", "Создаёт backup", "Отключает FK"], [0],
      "IDENTITY/serial sequences обнуляются."),
    q("q3", "single", "ON DELETE CASCADE при DELETE FROM parent:",
      ["Удаляет связанные дочерние строки", "Запрещает DELETE", "Обнуляет FK", "Создаёт VIEW"], [0],
      "CASCADE распространяет удаление."),
    q("q4", "single", "DELETE ... RETURNING:",
      ["Возвращает удалённые строки", "Откатывает DELETE", "Создаёт копию", "Только в TRUNCATE"], [0],
      "PostgreSQL поддерживает RETURNING для DELETE."),
    q("q5", "single", "TRUNCATE с CASCADE:",
      ["Очищает таблицы с FK ссылками на эту", "Только одну таблицу всегда", "Удаляет базу", "Создаёт индекс"], [0],
      "CASCADE для зависимых таблиц."),
    q("q6", "multi", "Когда использовать DELETE? (все верные)",
      ["Удалить часть строк", "Нужен WHERE", "Срабатывают DELETE-триггеры", "Полная очистка без триггеров — TRUNCATE"], [0, 1, 2],
      "Последний пункт — про TRUNCATE, не DELETE."),
]

QUIZZES["p3-l08-select-basics"] = [
    q("q1", "single", "SELECT DISTINCT:",
      ["Убирает полностью дублирующиеся строки", "Сортирует", "Фильтрует NULL", "Создаёт индекс"], [0],
      "DISTINCT — уникальные комбинации выбранных столбцов."),
    q("q2", "single", "LIMIT 10 OFFSET 20 — это:",
      ["Строки 21–30 при сортировке", "Первые 20", "Все строки", "Только COUNT"], [0],
      "OFFSET пропускает, LIMIT берёт следующие."),
    q("q3", "single", "AS в SELECT:",
      ["Задаёт псевдоним столбцу", "Создаёт таблицу", "Добавляет FK", "Фильтрует строки"], [0],
      "Alias для читаемости результата."),
    q("q4", "single", "SELECT * в production:",
      ["Не рекомендуется — лишние данные и хрупкость", "Обязательно", "Запрещено PostgreSQL", "Быстрее всего"], [0],
      "Явный список столбцов — best practice."),
    q("q5", "single", "Порядок выполнения: LIMIT после:",
      ["ORDER BY", "FROM", "GROUP BY", "HAVING"], [0],
      "LIMIT/OFFSET — последние в цепочке (после ORDER BY)."),
    q("q6", "multi", "Результат SELECT — это: (все верные)",
      ["Виртуальная таблица", "Множество строк", "Именованные столбцы", "Физическая таблица на диске"], [0, 1, 2],
      "Результат не сохраняется без CREATE TABLE AS."),
]

QUIZZES["p3-l09-where-order"] = [
    q("q1", "single", "WHERE email = NULL:",
      ["Всегда не находит строк (нужен IS NULL)", "Находит NULL", "Синтаксическая ошибка", "Эквивалент IS NULL"], [0],
      "NULL не сравнивается через =."),
    q("q2", "single", "LIKE 'Иван_' — символ _ означает:",
      ["Ровно один любой символ", "Любую строку", "Только цифру", "Escape"], [0],
      "_ — один символ, % — любая последовательность."),
    q("q3", "single", "BETWEEN a AND b включает:",
      ["Границы a и b", "Только a", "Не включает границы", "Только NULL"], [0],
      "BETWEEN inclusive с обеих сторон."),
    q("q4", "single", "ORDER BY last_name DESC, first_name ASC:",
      ["Сначала фамилия по убыванию, потом имя по возрастанию", "Только одна сортировка",
       "Случайный порядок", "Ошибка"], [0],
      "Множественная сортировка слева направо."),
    q("q5", "single", "IN (1, 2, 3) эквивалентно:",
      ["= 1 OR = 2 OR = 3", "AND всех", "BETWEEN", "LIKE"], [0],
      "IN — сокращение OR для списка."),
    q("q6", "multi", "Логические операторы SQL: (все верные)",
      ["AND", "OR", "NOT", "XOR — стандартный в SQL"], [0, 1, 2],
      "XOR не стандартный оператор SQL (есть обход через OR/AND)."),
]

QUIZZES["p3-l10-joins-intro"] = [
    q("q1", "single", "INNER JOIN возвращает:",
      ["Строки с совпадением в обеих таблицах", "Все строки левой", "Декартово произведение", "Только NULL"], [0],
      "Inner — пересечение по условию ON."),
    q("q2", "single", "ON в JOIN задаёт:",
      ["Условие соединения", "Сортировку", "GROUP BY", "LIMIT"], [0],
      "ON — предикат соединения."),
    q("q3", "single", "USING (col) возможен когда:",
      ["Столбец col есть в обеих таблицах с одним именем", "Только в одной таблице",
       "col — PRIMARY KEY только одной", "Никогда"], [0],
      "USING — сокращение для одинаковых имён."),
    q("q4", "single", "LEFT OUTER JOIN сохраняет:",
      ["Все строки левой таблицы", "Все строки правой", "Только совпадения", "Ни одной без пары"], [0],
      "LEFT — левая таблица полностью."),
    q("q5", "single", "JOIN нужен потому что:",
      ["Данные нормализованы по таблицам", "SELECT не работает без JOIN",
       "PostgreSQL требует", "Заменяет WHERE"], [0],
      "Нормализация → связи → JOIN."),
    q("q6", "multi", "Типы соединений: (все верные)",
      ["INNER", "LEFT", "CROSS", "HAVING"], [0, 1, 2],
      "HAVING — фильтр групп, не JOIN."),
]

QUIZZES["p3-l11-inner-join"] = [
    q("q1", "single", "Студент без записи в student_in_group при INNER JOIN с группой:",
      ["Не попадёт в результат", "Появится с NULL", "Вызовет ошибку", "Дублируется"], [0],
      "INNER отбрасывает строки без пары."),
    q("q2", "single", "JOIN ... ON a.id = b.id AND b.active — фильтр лучше в:",
      ["ON если сохраняем OUTER; WHERE для INNER", "Всегда только WHERE", "LIMIT", "HAVING"], [0],
      "Для OUTER условие на правую таблицу — в ON."),
    q("q3", "single", "Три таблицы в JOIN — порядок для читаемости:",
      ["FROM факт → JOIN справочники", "Случайный", "Только CROSS", "Без ON"], [0],
      "Центральная таблица + справочники."),
    q("q4", "single", "FROM a, b WHERE a.id = b.id без JOIN:",
      ["Эквивалент INNER JOIN, но менее читаем", "FULL OUTER", "ERROR", "CROSS JOIN всегда"], [0],
      "Старый стиль theta-join через WHERE."),
    q("q5", "single", "Составной JOIN по двум столбцам требует:",
      ["AND между условиями", "OR между условиями", "Только USING", "TRUNCATE"], [0],
      "Оба столбца должны совпасть."),
    q("q6", "single", "INNER JOIN student и performance даст:",
      ["Только студентов с оценками", "Всех студентов", "Только без оценок", "Пустой результат"], [0],
      "Inner — только совпадения."),
]

QUIZZES["p3-l12-outer-join"] = [
    q("q1", "single", "LEFT JOIN: строки правой без пары слева:",
      ["Не появятся", "Появятся с NULL слева", "Появятся полностью", "Ошибка"], [0],
      "LEFT сохраняет только левую."),
    q("q2", "single", "WHERE right_col IS NULL после LEFT JOIN находит:",
      ["Строки левой без пары справа", "Все строки", "Только NULL таблицу", "Дубликаты"], [0],
      "Anti-join pattern."),
    q("q3", "single", "FULL OUTER JOIN:",
      ["Все строки обеих таблиц", "Только INNER", "Только LEFT", "CROSS"], [0],
      "FULL = LEFT + RIGHT."),
    q("q4", "single", "Фильтр WHERE на столбец правой таблицы после LEFT JOIN:",
      ["Может превратить LEFT в INNER", "Без эффекта", "Ошибка", "Создаёт VIEW"], [0],
      "WHERE отфильтрует NULL-строки."),
    q("q5", "single", "RIGHT JOIN можно заменить:",
      ["LEFT JOIN с перестановкой таблиц", "CROSS JOIN", "UNION", "TRUNCATE"], [0],
      "a RIGHT b = b LEFT a."),
    q("q6", "multi", "NULL при OUTER JOIN означает: (все верные)",
      ["Нет пары в другой таблице", "Не «ноль»", "Не пустая строка", "Ошибку СУБД"], [0, 1, 2],
      "NULL — отсутствие значения, не ошибка."),
]

QUIZZES["p3-l13-cross-self-join"] = [
    q("q1", "single", "CROSS JOIN двух таблиц по 100 строк:",
      ["10000 строк", "100", "200", "1000000"], [0],
      "Декартово произведение: n × m."),
    q("q2", "single", "SELF JOIN — это:",
      ["Соединение таблицы с собой через алиасы", "CROSS JOIN с VIEW", "UNION", "TRUNCATE"], [0],
      "Два экземпляра одной таблицы."),
    q("q3", "single", "a.student_id < b.student_id в SELF JOIN:",
      ["Исключает дубликаты пар и (A,A)", "Ускоряет индекс", "Создаёт FK", "Обязателен для INNER"], [0],
      "Канонический приём для пар."),
    q("q4", "single", "CROSS JOIN опасен потому что:",
      ["Может создать огромный результат", "Удаляет данные", "Ломает PK", "Запрещён в PG"], [0],
      "Без условия — взрыв строк."),
    q("q5", "single", "Иерархия employee.manager_id → SELF JOIN:",
      ["Связывает сотрудника с руководителем", "Создаёт GROUP BY", "Только DELETE", "JSONB"], [0],
      "Классическое применение self join."),
    q("q6", "single", "INNER JOIN ON TRUE эквивалентен:",
      ["CROSS JOIN", "LEFT JOIN", "EXCEPT", "HAVING"], [0],
      "TRUE — нет фильтра соединения."),
]

QUIZZES["p3-l14-group-by"] = [
    q("q1", "single", "GROUP BY нужен когда:",
      ["В SELECT есть агрегаты и неагрегированные столбцы", "Только ORDER BY", "Только JOIN", "TRUNCATE"], [0],
      "Группировка для агрегирования."),
    q("q2", "single", "COUNT(*) vs COUNT(email):",
      ["COUNT(*) — все строки; COUNT(email) — без NULL email", "Одинаковы", "COUNT(*) быстрее NULL", "COUNT(email) считает NULL"], [0],
      "COUNT(column) игнорирует NULL."),
    q("q3", "single", "AVG(grade) при grade NULL:",
      ["NULL не участвует в среднем", "Среднее = 0", "Ошибка", "COUNT уменьшается на все строки"], [0],
      "Агрегаты игнорируют NULL (кроме COUNT(*))."),
    q("q4", "single", "GROUP BY g.name, g.course_num при SELECT g.name:",
      ["Корректно если оба в GROUP BY", "Ошибка", "Нужен HAVING", "Нужен CROSS JOIN"], [0],
      "Все неагрегированные столбцы SELECT ∈ GROUP BY."),
    q("q5", "single", "SUM(hours) по subject — группировка:",
      ["GROUP BY subject_id или name", "Только ORDER BY", "Без GROUP BY", "TRUNCATE"], [0],
      "Одна сумма на группу."),
    q("q6", "multi", "Агрегатные функции: (все верные)",
      ["COUNT", "SUM", "AVG", "JOIN"], [0, 1, 2],
      "JOIN — не агрегат."),
]

QUIZZES["p3-l15-having"] = [
    q("q1", "single", "HAVING применяется:",
      ["После GROUP BY к группам", "До GROUP BY", "Вместо WHERE", "Только в INSERT"], [0],
      "HAVING фильтрует агрегированные группы."),
    q("q2", "single", "WHERE AVG(grade) > 4:",
      ["Ошибка — нужен HAVING", "Корректно", "Эквивалент HAVING", "Только в PostgreSQL запрещено"], [0],
      "Агрегаты в WHERE недопустимы (обычно)."),
    q("q3", "single", "HAVING COUNT(*) > 5 после GROUP BY g.name:",
      ["Оставляет группы с более 5 строк", "Фильтрует строки до группировки", "Сортирует", "JOIN"], [0],
      "HAVING — условие на группы."),
    q("q4", "single", "WHERE и HAVING в одном запросе:",
      ["WHERE до группировки, HAVING после", "Только один из них", "HAVING первым", "Без GROUP BY"], [0],
      "Комбинация типична."),
    q("q5", "single", "HAVING без GROUP BY но с агрегатом:",
      ["Вся таблица — одна группа", "Ошибка всегда", "Эквивалент WHERE", "CROSS JOIN"], [0],
      "Неявная одна группа."),
    q("q6", "single", "Отличие WHERE от HAVING:",
      ["WHERE — строки; HAVING — группы", "Нет отличий", "HAVING быстрее", "WHERE только с JOIN"], [0],
      "Фундаментальное различие."),
]

QUIZZES["p3-l16-subqueries"] = [
    q("q1", "single", "Скalarный подзапрос возвращает:",
      ["Одно значение (одна строка, один столбец)", "Много столбцов", "Только NULL", "Таблицу без LIMIT"], [0],
      "Scalar — одно значение."),
    q("q2", "single", "EXISTS проверяет:",
      ["Наличие хотя бы одной строки в подзапросе", "Равенство всех", "UNIQUE", "COUNT = 0"], [0],
      "EXISTS TRUE если подзапрос не пуст."),
    q("q3", "single", "NOT IN с NULL в подзапросе:",
      ["Может дать пустой результат", "Работает как NOT EXISTS всегда", "Ошибка", "Игнорирует NULL"], [0],
      "Трёхзначная логика — ловушка NOT IN."),
    q("q4", "single", "Подзапрос во FROM:",
      ["Производная таблица с алиасом", "Ошибка", "Только VIEW", "TRIGGER"], [0],
      "Derived table / subquery in FROM."),
    q("q5", "single", "WHERE grade > (SELECT AVG(grade) FROM performance):",
      ["Скalar subquery", "EXISTS", "UNION", "CROSS JOIN"], [0],
      "AVG возвращает одно число."),
    q("q6", "multi", "Подзапрос можно использовать в: (все верные)",
      ["WHERE", "FROM", "SELECT (scalar)", "TRUNCATE"], [0, 1, 2],
      "TRUNCATE не использует SELECT."),
]

QUIZZES["p3-l17-set-ops"] = [
    q("q1", "single", "UNION vs UNION ALL:",
      ["UNION убирает дубликаты; ALL сохраняет все", "Одинаковы", "ALL убирает дубликаты", "UNION быстрее ALL"], [0],
      "ALL без distinct sort."),
    q("q2", "single", "INTERSECT:",
      ["Строки в обоих результатах", "Только в первом", "Объединение", "Разность"], [0],
      "Пересечение множеств."),
    q("q3", "single", "EXCEPT:",
      ["Строки из первого без второго", "Симметричная разность", "UNION", "JOIN"], [0],
      "A EXCEPT B = A − B."),
    q("q4", "single", "UNION требует:",
      ["Одинаковое число совместимых столбцов", "Одинаковые имена таблиц", "GROUP BY", "FK"], [0],
      "Совместимость типов столбцов."),
    q("q5", "single", "ORDER BY после UNION:",
      ["Применяется ко всему результату", "К каждому SELECT отдельно только", "Запрещён", "Только ASC"], [0],
      "ORDER BY в конце compound query."),
    q("q6", "single", "EXCEPT ALL в PostgreSQL:",
      ["Разность с учётом кратности", "Не существует", "Только INTERSECT", "Аналог TRUNCATE"], [0],
      "ALL варианты для multiset."),
]

QUIZZES["p3-l18-scalar-funcs"] = [
    q("q1", "single", "COALESCE(a, b, c):",
      ["Первый не-NULL аргумент", "Сумма", "Конкатенация", "MIN"], [0],
      "COALESCE — замена NULL."),
    q("q2", "single", "EXTRACT(YEAR FROM birth_date):",
      ["Извлекает год из даты", "Создаёт DATE", "Форматирует строку", "Индекс"], [0],
      "EXTRACT — часть даты/времени."),
    q("q3", "single", "UPPER(last_name):",
      ["Верхний регистр", "Длина строки", "Обрезка", "Число"], [0],
      "Строковая функция."),
    q("q4", "single", "NULLIF(a, b):",
      ["NULL если a = b, иначе a", "COALESCE", "MIN", "COUNT"], [0],
      "NULLIF — обратная COALESCE для равенства."),
    q("q5", "single", "NOW() возвращает:",
      ["Текущий timestamp", "Только date", "INTERVAL", "SERIAL"], [0],
      "Текущее время транзакции."),
    q("q6", "multi", "Функции даты: (все верные)",
      ["AGE", "DATE_TRUNC", "INTERVAL + DATE", "CROSS JOIN"], [0, 1, 2],
      "CROSS JOIN не функция даты."),
]

QUIZZES["p3-l19-case-when"] = [
    q("q1", "single", "CASE WHEN grade = 5 THEN 'A' ELSE 'B' END:",
      ["Условное выражение", "Ограничение CHECK", "JOIN", "VIEW"], [0],
      "CASE — ветвление в SELECT."),
    q("q2", "single", "Приведение ::numeric(4,2):",
      ["PostgreSQL cast синтаксис", "Комментарий", "Схема", "TRUNCATE"], [0],
      ":: — оператор приведения PG."),
    q("q3", "single", "COUNT(CASE WHEN x THEN 1 END):",
      ["Условный подсчёт", "Ошибка", "TRUNCATE", "UNION"], [0],
      "Conditional aggregation."),
    q("q4", "single", "CAST(x AS INTEGER) vs x::INTEGER:",
      ["Эквивалентны в PostgreSQL", "Разные типы", "CAST запрещён", "Только ::"], [0],
      "Два синтаксиса приведения."),
    q("q5", "single", "CASE без ELSE:",
      ["NULL если ни WHEN не сработал", "Ошибка", "0", "Пустая строка"], [0],
      "ELSE NULL по умолчанию."),
    q("q6", "single", "Вычисляемый столбец в SELECT:",
      ["Не хранится в таблице", "Добавляет столбец в DDL", "Создаёт index", "Trigger"], [0],
      "Вычисляется при запросе."),
]

QUIZZES["p3-l20-transactions"] = [
    q("q1", "single", "COMMIT:",
      ["Фиксирует транзакцию", "Откатывает", "Создаёт SAVEPOINT", "DELETE"], [0],
      "COMMIT — durability."),
    q("q2", "single", "A в ACID — Atomicity:",
      ["Всё или ничего", "Изоляция", "Согласованность схемы", "Индексы"], [0],
      "Atomicity — неделимость."),
    q("q3", "single", "ROLLBACK после ошибки в транзакции:",
      ["Отменяет все изменения транзакции", "Только последний INSERT", "Фиксирует", "TRUNCATE"], [0],
      "ROLLBACK — undo transaction."),
    q("q4", "single", "SAVEPOINT sp1; ROLLBACK TO sp1:",
      ["Откат до точки, COMMIT до sp1 сохраняется", "Полный ROLLBACK", "COMMIT", "DROP"], [0],
      "Частичный откат."),
    q("q5", "single", "В psql без BEGIN каждая команда:",
      ["Autocommit — отдельная транзакция", "В одной транзакции", "Не выполняется", "ROLLBACK"], [0],
      "По умолчанию autocommit on."),
    q("q6", "multi", "ACID: (все верные)",
      ["Atomicity", "Consistency", "Isolation", "Indexing"], [0, 1, 2],
      "D = Durability, не Indexing."),
]

QUIZZES["p3-l21-isolation"] = [
    q("q1", "single", "Уровень по умолчанию в PostgreSQL:",
      ["READ COMMITTED", "SERIALIZABLE", "READ UNCOMMITTED", "NONE"], [0],
      "PG default — READ COMMITTED."),
    q("q2", "single", "Dirty read — это:",
      ["Чтение незафиксированных данных", "Phantom", "Deadlock", "Index scan"], [0],
      "Uncommitted data visible."),
    q("q3", "single", "REPEATABLE READ в PG:",
      ["Snapshot на начало транзакции", "Dirty read возможен", "Без MVCC", "TRUNCATE only"], [0],
      "Consistent snapshot."),
    q("q4", "single", "Phantom read — появление:",
      ["Новых строк при повторном запросе", "NULL", "Deadlock", "Index bloat"], [0],
      "Phantoms — новые кортежи."),
    q("q5", "single", "SET TRANSACTION ISOLATION LEVEL:",
      ["Для текущей транзакции", "Глобально навсегда", "Только для VIEW", "DDL"], [0],
      "На уровень текущей транзакции."),
    q("q6", "single", "SERIALIZABLE может вызвать:",
      ["serialization_failure и нужен retry", "Dirty read", "TRUNCATE", "UNLOGGED table"], [0],
      "SSI — конфликты сериализации."),
]

QUIZZES["p3-l22-views"] = [
    q("q1", "single", "VIEW — это:",
      ["Сохранённый SELECT как виртуальная таблица", "Физическая копия", "Индекс", "Trigger"], [0],
      "View = stored query."),
    q("q2", "single", "MATERIALIZED VIEW:",
      ["Хранит результат физически", "Обновляется автоматически всегда", "Не SELECT", "Только TEMP"], [0],
      "Нужен REFRESH."),
    q("q3", "single", "REFRESH MATERIALIZED VIEW:",
      ["Пересчитывает данные MV", "DELETE", "DROP", "GRANT"], [0],
      "Явное обновление snapshot."),
    q("q4", "single", "VIEW используют для:",
      ["Упрощения запросов и безопасности", "TRUNCATE базы", "WAL", "Partition"], [0],
      "Abstraction layer."),
    q("q5", "single", "SELECT * FROM v_student_groups:",
      ["Выполняет underlying query", "Читает disk copy всегда", "Только INSERT", "CROSS JOIN"], [0],
      "Обычный view — live query."),
    q("q6", "multi", "Обновляемый VIEW возможен когда: (все верные)",
      ["Одна базовая таблица (упрощённо)", "Нет агрегатов (упрощённо)", "Сложные — через INSTEAD OF trigger", "Всегда любой VIEW"], [0, 1, 2],
      "Сложные view read-only по умолчанию."),
]

QUIZZES["p3-l23-triggers"] = [
    q("q1", "single", "BEFORE INSERT trigger может:",
      ["Изменить NEW или отменить строку (RETURN NULL)", "Только логировать после", "COMMIT", "CREATE INDEX"], [0],
      "BEFORE row trigger — модификация/отмена."),
    q("q2", "single", "FOR EACH ROW:",
      ["Срабатывает на каждую строку", "Один раз на statement", "Только SELECT", "VIEW"], [0],
      "Row-level granularity."),
    q("q3", "single", "NEW и OLD в trigger:",
      ["NEW — новая версия; OLD — прежняя", "Только имена таблиц", "SERIAL", "Schema"], [0],
      "Строковые переменные PL/pgSQL."),
    q("q4", "single", "AFTER UPDATE trigger:",
      ["После изменения строки", "До проверки FK", "Вместо INSERT", "DDL only"], [0],
      "AFTER — post-operation."),
    q("q5", "single", "TG_OP содержит:",
      ["INSERT, UPDATE, DELETE", "SELECT", "COMMIT", "JOIN type"], [0],
      "Тип операции DML."),
    q("q6", "single", "Триггер для аудита:",
      ["Типичное применение AFTER", "Заменяет все FK", "Удаляет WAL", "Только VIEW"], [0],
      "Audit log on changes."),
]

QUIZZES["p3-l24-exam"] = [
    q("q1", "single", "Частая ошибка: WHERE col = NULL. Правильно:",
      ["col IS NULL", "col = 'NULL'", "ISNULL(col)", "col == NULL"], [0],
      "Трёхзначная логика SQL."),
    q("q2", "single", "DELETE без WHERE:",
      ["Удалит все строки", "Ошибка", "Одну строку", "TRUNCATE TABLE автоматически"], [0],
      "Опасный DML."),
    q("q3", "single", "Столбец в SELECT не в GROUP BY и не агрегат:",
      ["Ошибка (в стандартном SQL)", "OK всегда", "Только в PostgreSQL OK", "HAVING fix"], [0],
      "Правило группировки."),
    q("q4", "multi", "DDL команды: (все верные)",
      ["CREATE TABLE", "ALTER TABLE", "DROP TABLE", "SELECT"], [0, 1, 2],
      "SELECT — DML/query."),
    q("q5", "single", "INNER JOIN vs LEFT JOIN для «все группы и студенты»:",
      ["LEFT JOIN — сохранит пустые группы", "INNER", "CROSS", "EXCEPT"], [0],
      "Outer для сохранения без пары."),
    q("q6", "single", "Транзакция при ошибке в середине:",
      ["ROLLBACK отменяет всё с BEGIN", "COMMIT частично", "Autocommit откатывает всю БД", "TRUNCATE"], [0],
      "Atomicity транзакции."),
]
